name: Prod Test

on:
    workflow_dispatch:  # Allow manual triggering

jobs:
  publish:
    permissions:
      contents: write
      packages: write
      pull-requests: write

    runs-on:
      labels: [self-hosted, dev-image-builder]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.PROD_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.PROD_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Upload files to S3 with AWS CLI
        run: |
            aws sts get-caller-identity
            aws s3 ls
            ls -l 
            aws s3 sync ./assets/ s3://assets.virtualinternships.com/base-table --delete